/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 04-may.-2024 4:49:20 a. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

 

 

 

 

 

 

/* Drop Tables */

DROP TABLE IF EXISTS cart CASCADE
;

DROP TABLE IF EXISTS category CASCADE
;

DROP TABLE IF EXISTS department CASCADE
;

DROP TABLE IF EXISTS employee CASCADE
;

DROP TABLE IF EXISTS inventory CASCADE
;

DROP TABLE IF EXISTS physical_location CASCADE
;

DROP TABLE IF EXISTS product CASCADE
;

DROP TABLE IF EXISTS purchase CASCADE
;

/* Create Tables */

CREATE TABLE cart
(
	pk_fk_product integer NOT NULL,	-- Identifier of the product in the cart associated with the purchase
	pk_fk_purchase integer NOT NULL,	-- Identifier of the purchase that the product belongs to
	amount smallint NOT NULL,	-- Amount of the product that belongs to the purchase
	unit_price smallint NOT NULL	-- Price of an unit of the product.
)
;

CREATE TABLE category
(
	pk_id serial NOT NULL,	-- Category identifier
	name varchar(25) NULL,	-- Category name
	description varchar(250) NULL	-- Short description of the type of product included in the category
)
;

CREATE TABLE department
(
	pk_id serial NOT NULL,	-- Department identifier
	name varchar(50) NOT NULL	-- Department name
)
;

CREATE TABLE employee
(
	pk_id serial NOT NULL,	-- Employee identifier
	fk_physical_location integer NULL,	-- Identify the physical point that the employee belongs to. This field can be NULL if its role is administrator
	name varchar(25) NOT NULL,	-- Employee name
	last_name varchar(25) NOT NULL,	-- Employee last name
	telephone varchar(15) NOT NULL,	-- Employee telephone It must be a number and can't begin with 0
	role varchar(13) NOT NULL,	-- Employee role in the company, depending on its value, the employee will have a specific set of permissions. Only the following values should be allowed:      - Administrator     - Manager     - Cashier
	password varchar(300) NOT NULL	-- Employee password for get access
)
;

CREATE TABLE inventory
(
	pk_fk_product integer NOT NULL,	-- Identifier of the product stored in the inventory associated with a physical location
	pk_fk_physical_location integer NOT NULL,	-- Identifier of the physical location that own of the inventory
	amount smallint NOT NULL	-- Amount of the product stored at the physical location
)
;

CREATE TABLE physical_location
(
	pk_id serial NOT NULL,	-- Physical location identifier
	direction varchar(55) NOT NULL,	-- Physical location address
	telephone varchar(15) NOT NULL	-- The telephone number of the physical location. It must be a number and can't begin with 0
)
;

CREATE TABLE product
(
	pk_id serial NOT NULL,	-- Identifier of product
	fk_id_base_product integer NULL,	-- Given that the products can have variants. This field has the identifier of base product.
	name varchar(25) NOT NULL,	-- Name of product
	description varchar(250) NOT NULL,	-- Short description of the product
	price integer NOT NULL,	-- Sell price of product
	image text NOT NULL,	-- File name that contains the image of the product
	fk_category integer NOT NULL	-- References the category that the product belongs to
)
;

CREATE TABLE purchase
(
	pk_id serial NOT NULL,	-- Identificador de la compra
	date date NOT NULL,	-- Date when the purchase was made
	total_price integer NOT NULL,	-- Total purchase value It's dynamically calculated
	email varchar(75) NOT NULL,	-- Email address of the person who made the purchase Must be a valid email address in the form: abc@dfg.hi
	name varchar(45) NOT NULL,	-- Full Name of the shopper
	doc_type varchar(2) NOT NULL,	-- Type of the identification of the shopper Allowed values:     - CC     - TI     - CE In capital letters
	identification varchar(15) NOT NULL,	-- Identification number of the person who made the purchase Must be a number and can't begin with 0
	telephone varchar(15) NOT NULL,	-- Telephone number of the person who made the purchase
	is_physic_purchase boolean NOT NULL,	-- Indicates whether the purchase was made at a physical location or, alternatively, was made online
	delivery_address varchar(55) NULL,	-- Delivery address for online purchases. It only has a value if the purchase was online
	fk_department integer NULL,	-- Department where the delivery address is located It only has a value if the purchase was online
	zip_code varchar(6) NULL	-- Zip code corresponding to the delivery address It must be a number and can't begin with 0 It only has a value if the purchase was online
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE cart ADD CONSTRAINT "PK_cart"
	PRIMARY KEY (pk_fk_product,pk_fk_purchase)
;

CREATE INDEX "IXFK_cart_product" ON cart (pk_fk_product ASC)
;

CREATE INDEX "IXFK_cart_purchase" ON cart (pk_fk_purchase ASC)
;

ALTER TABLE category ADD CONSTRAINT "PK_category"
	PRIMARY KEY (pk_id)
;

ALTER TABLE department ADD CONSTRAINT "PK_department"
	PRIMARY KEY (pk_id)
;

ALTER TABLE employee ADD CONSTRAINT "PK_employee"
	PRIMARY KEY (pk_id)
;

ALTER TABLE employee ADD CONSTRAINT c_telephone CHECK (telephone ~* '^[1-9][0-9]*$')
;

ALTER TABLE employee ADD CONSTRAINT c_role_domain CHECK (employee.role in ('administrator', 'manager', 'cashier'))
;

CREATE INDEX "IXFK_employee_physical_location" ON employee (fk_physical_location ASC)
;

ALTER TABLE inventory ADD CONSTRAINT "PK_inventary"
	PRIMARY KEY (pk_fk_product,pk_fk_physical_location)
;

CREATE INDEX "IXFK_inventary_physical_location" ON inventory (pk_fk_physical_location ASC)
;

CREATE INDEX "IXFK_inventary_product" ON inventory (pk_fk_product ASC)
;

ALTER TABLE physical_location ADD CONSTRAINT "PK_physical_location"
	PRIMARY KEY (pk_id)
;

ALTER TABLE physical_location ADD CONSTRAINT c_telephone CHECK (telephone ~* '^[1-9][0-9]*$')
;

ALTER TABLE product ADD CONSTRAINT "PK_product"
	PRIMARY KEY (pk_id)
;

ALTER TABLE product ADD CONSTRAINT c_valor CHECK (price >= 0)
;

CREATE INDEX "IXFK_product_category" ON product (fk_category ASC)
;

ALTER TABLE purchase ADD CONSTRAINT "PK_purchase"
	PRIMARY KEY (pk_id)
;

ALTER TABLE purchase ADD CONSTRAINT c_email CHECK (email ~* '^[A-Za-z0-9._+%-]+@[A-Za-z0-9.-]+[.][A-Za-z]+$')
;

ALTER TABLE purchase ADD CONSTRAINT c_doc_type CHECK (doc_type IN ('CC', 'TI', 'CE'))
;

ALTER TABLE purchase ADD CONSTRAINT c_identification CHECK (identification ~* '^[1-9][0-9]*$')
;

ALTER TABLE purchase ADD CONSTRAINT c_purchase_type CHECK ((is_physic_purchase AND delivery_address IS NULL 
	AND fk_department IS NULL AND zip_code IS NULL) 
OR (NOT is_physic_purchase AND delivery_address IS NOT NULL 
	AND fk_department IS NOT NULL AND zip_code IS NOT NULL) )
;

CREATE INDEX "IXFK_purchase_department" ON purchase (fk_department ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE cart ADD CONSTRAINT "FK_cart_product"
	FOREIGN KEY (pk_fk_product) REFERENCES product (pk_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE cart ADD CONSTRAINT "FK_cart_purchase"
	FOREIGN KEY (pk_fk_purchase) REFERENCES purchase (pk_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE employee ADD CONSTRAINT "FK_employee_physical_location"
	FOREIGN KEY (fk_physical_location) REFERENCES physical_location (pk_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE inventory ADD CONSTRAINT "FK_inventary_physical_location"
	FOREIGN KEY (pk_fk_physical_location) REFERENCES physical_location (pk_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE inventory ADD CONSTRAINT "FK_inventary_product"
	FOREIGN KEY (pk_fk_product) REFERENCES product (pk_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE product ADD CONSTRAINT "FK_product_category"
	FOREIGN KEY (fk_category) REFERENCES category (pk_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE purchase ADD CONSTRAINT "FK_purchase_department"
	FOREIGN KEY (fk_department) REFERENCES department (pk_id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON COLUMN cart.pk_fk_product
	IS 'Identifier of the product in the cart associated with the purchase'
;

COMMENT ON COLUMN cart.pk_fk_purchase
	IS 'Identifier of the purchase that the product belongs to'
;

COMMENT ON COLUMN cart.amount
	IS 'Amount of the product that belongs to the purchase'
;

COMMENT ON COLUMN cart.unit_price
	IS 'Price of an unit of the product.'
;

COMMENT ON COLUMN category.pk_id
	IS 'Category identifier'
;

COMMENT ON COLUMN category.name
	IS 'Category name'
;

COMMENT ON COLUMN category.description
	IS 'Short description of the type of product included in the category'
;

 

COMMENT ON COLUMN department.pk_id
	IS 'Department identifier'
;

COMMENT ON COLUMN department.name
	IS 'Department name'
;

 

COMMENT ON COLUMN employee.pk_id
	IS 'Employee identifier'
;

COMMENT ON COLUMN employee.fk_physical_location
	IS 'Identify the physical point that the employee belongs to.
This field can be NULL if its role is administrator'
;

COMMENT ON COLUMN employee.name
	IS 'Employee name'
;

COMMENT ON COLUMN employee.last_name
	IS 'Employee last name'
;

COMMENT ON COLUMN employee.telephone
	IS 'Employee telephone
It must be a number and can''t begin with 0'
;

COMMENT ON COLUMN employee.role
	IS 'Employee role in the company, depending on its value, the employee will have a specific set of permissions. Only the following values should be allowed:

    - Administrator
    - Manager
    - Cashier'
;

COMMENT ON COLUMN employee.password
	IS 'Employee password for get access'
;

 

COMMENT ON COLUMN inventory.pk_fk_product
	IS 'Identifier of the product stored in the inventory associated with a physical location'
;

COMMENT ON COLUMN inventory.pk_fk_physical_location
	IS 'Identifier of the physical location that own of the inventory'
;

COMMENT ON COLUMN inventory.amount
	IS 'Amount of the product stored at the physical location'
;

COMMENT ON COLUMN physical_location.pk_id
	IS 'Physical location identifier'
;

COMMENT ON COLUMN physical_location.direction
	IS 'Physical location address'
;

COMMENT ON COLUMN physical_location.telephone
	IS 'The telephone number of the physical location.
It must be a number and can''t begin with 0'
;

 

COMMENT ON COLUMN product.pk_id
	IS 'Identifier of product'
;

COMMENT ON COLUMN product.fk_id_base_product
	IS 'Given that the products can have variants.
This field has the identifier of base product.'
;

COMMENT ON COLUMN product.name
	IS 'Name of product'
;

COMMENT ON COLUMN product.description
	IS 'Short description of the product'
;

COMMENT ON COLUMN product.price
	IS 'Sell price of product'
;

COMMENT ON COLUMN product.image
	IS 'File name that contains the image of the product'
;

COMMENT ON COLUMN product.fk_category
	IS 'References the category that the product belongs to'
;

COMMENT ON CONSTRAINT c_valor ON product IS 'The price field must be positive'
;

 

COMMENT ON COLUMN purchase.pk_id
	IS 'Identificador de la compra'
;

COMMENT ON COLUMN purchase.date
	IS 'Date when the purchase was made'
;

COMMENT ON COLUMN purchase.total_price
	IS 'Total purchase value
It''s dynamically calculated'
;

COMMENT ON COLUMN purchase.email
	IS 'Email address of the person who made the purchase
Must be a valid email address in the form: abc@dfg.hi'
;

COMMENT ON COLUMN purchase.name
	IS 'Full Name of the shopper'
;

COMMENT ON COLUMN purchase.doc_type
	IS 'Type of the identification of the shopper
Allowed values:
    - CC
    - TI
    - CE
In capital letters'
;

COMMENT ON COLUMN purchase.identification
	IS 'Identification number of the person who made the purchase
Must be a number and can''t begin with 0'
;

COMMENT ON COLUMN purchase.telephone
	IS 'Telephone number of the person who made the purchase'
;

COMMENT ON COLUMN purchase.is_physic_purchase
	IS 'Indicates whether the purchase was made at a physical location or, alternatively, was made online'
;

COMMENT ON COLUMN purchase.delivery_address
	IS 'Delivery address for online purchases.
It only has a value if the purchase was online'
;

COMMENT ON COLUMN purchase.fk_department
	IS 'Department where the delivery address is located
It only has a value if the purchase was online'
;

COMMENT ON COLUMN purchase.zip_code
	IS 'Zip code corresponding to the delivery address
It must be a number and can''t begin with 0
It only has a value if the purchase was online'
;

 
