/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 05-may.-2024 12:47:57 a. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

 

 

 

 

 

/* Drop Tables */

DROP TABLE IF EXISTS carrito CASCADE
;

DROP TABLE IF EXISTS categoria CASCADE
;

DROP TABLE IF EXISTS compra CASCADE
;

DROP TABLE IF EXISTS empleado CASCADE
;

DROP TABLE IF EXISTS inventario CASCADE
;

DROP TABLE IF EXISTS producto CASCADE
;

DROP TABLE IF EXISTS punto_fisico CASCADE
;

/* Create Tables */

CREATE TABLE carrito
(
	pk_fk_producto integer NOT NULL,	-- Identificador del producto en el carrito asociado a la compra
	pk_fk_compra integer NOT NULL,	-- Identificador de la compra a la que pertenece el carrito
	cantidad smallint NOT NULL,	-- Cantidd del producto perteneciente a la compra
	precio smallint NOT NULL	-- Precio con al que se cobró cada unidad del producto al momento de hacer la compra
)
;

CREATE TABLE categoria
(
	pk_id serial NOT NULL,	-- Identificador de la categoría
	nombre varchar(25) NULL,	-- Nombre de la categoría
	descripcion varchar(250) NULL	-- Descripción corta del tipo de producto que abarca la categoria
)
;

CREATE TABLE compra
(
	pk_id serial NOT NULL,	-- Identificador de la compra
	fecha date NOT NULL,	-- Fecha en la que se realizó la compra
	valor_pagado integer NOT NULL,	-- Valor del total de los productos comprados  Se calcula
	correo varchar(75) NOT NULL,	-- El correo de la persona que realiza la compra  Debe ser un correo valido de la forma abc@dfg.hi
	tipo_doc varchar(2) NOT NULL,	-- Tipo de identificacion del comprador  Valores permitidos:     - CC     - TI     - CE Todos en mayúsuclas
	identificacion varchar(15) NOT NULL,	-- Número de identificacion de la persona que realizó la compra Debe ser un número, y no puede empezar por 0
	tipo_fisica boolean NOT NULL,	-- Indica si la compra fue en un punto fisico o de lo contrario fue en línea
	direccion_entrega varchar(55) NULL	-- Dirección de la entrega del producto para compras en línea  Solo tiene valor para compras en linea
)
;

CREATE TABLE empleado
(
	pk_id serial NOT NULL,	-- Identificador del empleado
	fk_punto_fisico integer NULL,	-- Identifica el punto fisico al cual pertenece el empleado Este campo puede ser NULL si el rol es  'administrador'
	nombre varchar(50) NOT NULL,	-- Nombre del empleado
	apellido varchar(50) NOT NULL,	-- Apellido del empleado
	telefono varchar(15) NOT NULL,	-- Teléfono del empleado. Debe ser un número, y no puede empezar por 0
	rol varchar(13) NOT NULL,	-- Rol del empleado en la empresa, dependiendo de su valor el empleado tendrá una variedad específica de permisos Solo deben estar permitidos los valores:     - administrador     - gerente     - cajero
	contrasena varchar(300) NOT NULL	-- Contraseña del usuario
)
;

CREATE TABLE inventario
(
	pk_fk_producto integer NOT NULL,	-- Identificador del producto almacenado en el inventario asociado a un punto físico
	pk_fk_punto_fisico integer NOT NULL,	-- Identificador del punto físico al cual pertenece el inventario
	cantidad smallint NOT NULL	-- Cantidad del producto en el punto fisico
)
;

CREATE TABLE producto
(
	pk_id serial NOT NULL,	-- Identificador del producto
	fk_id_prod_base integer NULL,	-- Considerando que un mismo producto puede tener variantes. Este campo contiene el identificador del producto base
	nombre varchar(25) NOT NULL,	-- Nombre del producto
	descripcion varchar(250) NOT NULL,	-- Descripción corta del producto
	valor integer NOT NULL,	-- Valor o precio a la que se vente el producto
	imagen varchar(50) NOT NULL,	-- Nombre del archivo que contiene la imagen del producto
	fk_categoria integer NOT NULL	-- Referencia a la categoría a que pertenece el producto
)
;

CREATE TABLE punto_fisico
(
	pk_id serial NOT NULL,	-- Identificador del punto fisico
	direccion varchar(55) NOT NULL,	-- Dirección del punto fisico
	telefono varchar(15) NOT NULL	-- Numero telefónico del punto fisico, importante para una comunicacion directa. Debe ser un número, y no puede empezar por 0
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE carrito ADD CONSTRAINT "PK_carrito"
	PRIMARY KEY (pk_fk_producto,pk_fk_compra)
;

CREATE INDEX "IXFK_carrito_compra" ON carrito (pk_fk_compra ASC)
;

CREATE INDEX "IXFK_carrito_producto" ON carrito (pk_fk_producto ASC)
;

ALTER TABLE categoria ADD CONSTRAINT "PK_categoria"
	PRIMARY KEY (pk_id)
;

ALTER TABLE compra ADD CONSTRAINT "PK_compra"
	PRIMARY KEY (pk_id)
;

ALTER TABLE compra ADD CONSTRAINT c_correo CHECK (correo ~* '^[A-Za-z0-9._+%-]+@[A-Za-z0-9.-]+[.][A-Za-z]+$')
;

ALTER TABLE compra ADD CONSTRAINT c_tipo_doc CHECK (tipo_doc IN ('CC', 'TI', 'CE'))
;

ALTER TABLE compra ADD CONSTRAINT c_identificacion CHECK (identificacion ~* '^[1-9][0-9]*$')
;

ALTER TABLE compra ADD CONSTRAINT c_tipo_de_compra CHECK ((tipo_fisica AND direccion_entrega IS NULL) 
  OR (NOT tipo_fisica AND direccion_entrega IS NOT NULL))
;

ALTER TABLE empleado ADD CONSTRAINT "PK_empleado"
	PRIMARY KEY (pk_id)
;

ALTER TABLE empleado ADD CONSTRAINT c_telefono CHECK (telefono ~* '^[1-9][0-9]*$')
;

ALTER TABLE empleado ADD CONSTRAINT c_dominio_rol CHECK (rol IN ('cajero', 'gerente', 'administrador'))
;

ALTER TABLE empleado ADD CONSTRAINT c_rol_punt_fisico CHECK ((empleado.fk_punto_fisico IS NULL and empleado.rol = 'administrador')
  OR empleado.fk_punto_fisico IS NOT NULL)
;

CREATE INDEX "IXFK_empleado_punto_fisico" ON empleado (fk_punto_fisico ASC)
;

ALTER TABLE inventario ADD CONSTRAINT "PK_inventario"
	PRIMARY KEY (pk_fk_producto,pk_fk_punto_fisico)
;

CREATE INDEX "IXFK_inventario_producto" ON inventario (pk_fk_producto ASC)
;

CREATE INDEX "IXFK_inventario_punto_fisico" ON inventario (pk_fk_punto_fisico ASC)
;

ALTER TABLE producto ADD CONSTRAINT "PK_Table A"
	PRIMARY KEY (pk_id)
;

ALTER TABLE producto ADD CONSTRAINT c_valor CHECK (valor >= 0)
;

CREATE INDEX "IXFK_producto_categoria" ON producto (fk_categoria ASC)
;

ALTER TABLE punto_fisico ADD CONSTRAINT "PK_punto_fisico"
	PRIMARY KEY (pk_id)
;

ALTER TABLE punto_fisico ADD CONSTRAINT c_telefono CHECK (telefono ~* '^[1-9][0-9]*$')
;

/* Create Foreign Key Constraints */

ALTER TABLE carrito ADD CONSTRAINT "FK_carrito_compra"
	FOREIGN KEY (pk_fk_compra) REFERENCES compra (pk_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE carrito ADD CONSTRAINT "FK_carrito_producto"
	FOREIGN KEY (pk_fk_producto) REFERENCES producto (pk_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE empleado ADD CONSTRAINT "FK_empleado_punto_fisico"
	FOREIGN KEY (fk_punto_fisico) REFERENCES punto_fisico (pk_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE inventario ADD CONSTRAINT "FK_inventario_producto"
	FOREIGN KEY (pk_fk_producto) REFERENCES producto (pk_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE inventario ADD CONSTRAINT "FK_inventario_punto_fisico"
	FOREIGN KEY (pk_fk_punto_fisico) REFERENCES punto_fisico (pk_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE producto ADD CONSTRAINT "FK_producto_categoria"
	FOREIGN KEY (fk_categoria) REFERENCES categoria (pk_id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE carrito
	IS 'Tabla de rompimiento para la relacion de compra y producto donde a una compra le corresponden una lista de productos'
;

COMMENT ON COLUMN carrito.pk_fk_producto
	IS 'Identificador del producto en el carrito asociado a la compra'
;

COMMENT ON COLUMN carrito.pk_fk_compra
	IS 'Identificador de la compra a la que pertenece el carrito'
;

COMMENT ON COLUMN carrito.cantidad
	IS 'Cantidd del producto perteneciente a la compra'
;

COMMENT ON COLUMN carrito.precio
	IS 'Precio con al que se cobró cada unidad del producto al momento de hacer la compra'
;

COMMENT ON COLUMN categoria.pk_id
	IS 'Identificador de la categoría'
;

COMMENT ON COLUMN categoria.nombre
	IS 'Nombre de la categoría'
;

COMMENT ON COLUMN categoria.descripcion
	IS 'Descripción corta del tipo de producto que abarca la categoria'
;

 

COMMENT ON COLUMN compra.pk_id
	IS 'Identificador de la compra'
;

COMMENT ON COLUMN compra.fecha
	IS 'Fecha en la que se realizó la compra'
;

COMMENT ON COLUMN compra.valor_pagado
	IS 'Valor del total de los productos comprados

Se calcula'
;

COMMENT ON COLUMN compra.correo
	IS 'El correo de la persona que realiza la compra

Debe ser un correo valido de la forma abc@dfg.hi'
;

COMMENT ON COLUMN compra.tipo_doc
	IS 'Tipo de identificacion del comprador

Valores permitidos:
    - CC
    - TI
    - CE
Todos en mayúsuclas'
;

COMMENT ON COLUMN compra.identificacion
	IS 'Número de identificacion de la persona que realizó la compra
Debe ser un número, y no puede empezar por 0'
;

COMMENT ON COLUMN compra.tipo_fisica
	IS 'Indica si la compra fue en un punto fisico o de lo contrario fue en línea'
;

COMMENT ON COLUMN compra.direccion_entrega
	IS 'Dirección de la entrega del producto para compras en línea

Solo tiene valor para compras en linea'
;

 

COMMENT ON COLUMN empleado.pk_id
	IS 'Identificador del empleado'
;

COMMENT ON COLUMN empleado.fk_punto_fisico
	IS 'Identifica el punto fisico al cual pertenece el empleado
Este campo puede ser NULL si el rol es  ''administrador'''
;

COMMENT ON COLUMN empleado.nombre
	IS 'Nombre del empleado'
;

COMMENT ON COLUMN empleado.apellido
	IS 'Apellido del empleado'
;

COMMENT ON COLUMN empleado.telefono
	IS 'Teléfono del empleado.
Debe ser un número, y no puede empezar por 0'
;

COMMENT ON COLUMN empleado.rol
	IS 'Rol del empleado en la empresa, dependiendo de su valor el empleado tendrá una variedad específica de permisos
Solo deben estar permitidos los valores:
    - administrador
    - gerente
    - cajero'
;

COMMENT ON COLUMN empleado.contrasena
	IS 'Contraseña del usuario'
;

 

COMMENT ON COLUMN inventario.pk_fk_producto
	IS 'Identificador del producto almacenado en el inventario asociado a un punto físico'
;

COMMENT ON COLUMN inventario.pk_fk_punto_fisico
	IS 'Identificador del punto físico al cual pertenece el inventario'
;

COMMENT ON COLUMN inventario.cantidad
	IS 'Cantidad del producto en el punto fisico'
;

COMMENT ON COLUMN producto.pk_id
	IS 'Identificador del producto'
;

COMMENT ON COLUMN producto.fk_id_prod_base
	IS 'Considerando que un mismo producto puede tener variantes.
Este campo contiene el identificador del producto base'
;

COMMENT ON COLUMN producto.nombre
	IS 'Nombre del producto'
;

COMMENT ON COLUMN producto.descripcion
	IS 'Descripción corta del producto'
;

COMMENT ON COLUMN producto.valor
	IS 'Valor o precio a la que se vente el producto'
;

COMMENT ON COLUMN producto.imagen
	IS 'Nombre del archivo que contiene la imagen del producto'
;

COMMENT ON COLUMN producto.fk_categoria
	IS 'Referencia a la categoría a que pertenece el producto'
;

 

COMMENT ON COLUMN punto_fisico.pk_id
	IS 'Identificador del punto fisico'
;

COMMENT ON COLUMN punto_fisico.direccion
	IS 'Dirección del punto fisico'
;

COMMENT ON COLUMN punto_fisico.telefono
	IS 'Numero telefónico del punto fisico, importante para una comunicacion directa.
Debe ser un número, y no puede empezar por 0'
;

 
