/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 04-may.-2024 12:19:56 a. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

 

 

 

 

 

 

/* Drop Tables */

DROP TABLE IF EXISTS category CASCADE
;

DROP TABLE IF EXISTS department CASCADE
;

DROP TABLE IF EXISTS ecommerce_purchase CASCADE
;

DROP TABLE IF EXISTS employee CASCADE
;

DROP TABLE IF EXISTS inventory CASCADE
;

DROP TABLE IF EXISTS physical_location CASCADE
;

DROP TABLE IF EXISTS physical_purchase CASCADE
;

DROP TABLE IF EXISTS product CASCADE
;

DROP TABLE IF EXISTS product_in_purchase CASCADE
;

DROP TABLE IF EXISTS product_request CASCADE
;

DROP TABLE IF EXISTS purchase CASCADE
;

/* Create Tables */

CREATE TABLE category
(
	pk_id serial NOT NULL,	-- Category identifier
	name varchar(25) NULL,	-- Category name
	description varchar(250) NULL	-- Short description of the type of product included in the category
)
;

CREATE TABLE department
(
	pk_id serial NOT NULL,	-- Department identifier
	name varchar(25) NOT NULL	-- Department name
)
;

CREATE TABLE ecommerce_purchase
(
	pk_fk_purchase integer NOT NULL,	-- Identifier of the base purchase
	fk_department integer NOT NULL,	-- Department where the delivery address is located
	delivery_address varchar(55) NOT NULL,	-- Delivery address for online purchases. It only has a value if the purchase was online
	zip_code varchar(6) NOT NULL	-- Zip code corresponding to the delivery address It must be a number and can't begin with 0 It only has a value if the purchase was online
)
;

CREATE TABLE employee
(
	pk_id serial NOT NULL,	-- Employee identifier
	fk_physical_location integer NULL,	-- Identify the physical point that the employee belongs to. This field can be NULL if its role is administrator
	name varchar(25) NOT NULL,	-- Employee name
	last_name varchar(25) NOT NULL,	-- Employee last name
	telephone varchar(15) NOT NULL,	-- Employee telephone It must be a number and can't begin with 0
	role varchar(13) NOT NULL,	-- Employee role in the company, depending on its value, the employee will have a specific set of permissions. Only the following values should be allowed:      - Administrator     - Manager     - Cashier
	password varchar(60) NOT NULL,	-- Employee password for get access
	doc_type varchar(2) NOT NULL,
	identification varchar(15) NOT NULL	-- Identification number of the employee Must be a number and can't begin with 0
)
;

CREATE TABLE inventory
(
	pk_fk_product integer NOT NULL,	-- Identifier of the product stored in the inventory associated with a physical location
	pk_fk_physical_location integer NOT NULL,	-- Identifier of the physical location that own of the inventory
	quantity smallint NOT NULL,	-- Amount of the product stored at the physical location
	display_quantity smallint NOT NULL,
	ecommerce_available_quantity smallint NOT NULL   DEFAULT 0
)
;

CREATE TABLE physical_location
(
	pk_id serial NOT NULL,	-- Physical location identifier
	direction varchar(55) NOT NULL,	-- Physical location address
	telephone varchar(15) NOT NULL	-- The telephone number of the physical location. It must be a number and can't begin with 0
)
;

CREATE TABLE physical_purchase
(
	pk_fk_purchase integer NOT NULL,	-- Identifier of the base purchase
	fk_employee integer NOT NULL
)
;

CREATE TABLE product
(
	pk_id serial NOT NULL,	-- Identifier of product
	fk_id_base_product integer NULL,	-- Given that the products can have variants. This field has the identifier of base product.
	name varchar(25) NOT NULL,	-- Name of product
	description varchar(250) NOT NULL,	-- Short description of the product
	price integer NOT NULL,	-- Sell price of product
	image text NOT NULL,	-- File name that contains the image of the product
	active boolean NOT NULL,	-- It indicates if the product should be visible in the store.
	fk_category integer NOT NULL	-- References the category that the product belongs to
)
;

CREATE TABLE product_in_purchase
(
	pk_fk_product integer NOT NULL,	-- Reference to product in the purchase
	pk_fk_purchase integer NOT NULL,	-- Reference to the purchase to which the product belongs
	quantity smallint NOT NULL,	-- Quantity of the product that belongs to the purchase
	unit_price integer NOT NULL	-- Price per unit of the product at the time the purchase was completed
)
;

CREATE TABLE product_request
(
	pk_fk_product integer NOT NULL,
	pk_fk_purchase integer NOT NULL,
	pk_fk_physical_location integer NOT NULL,	-- Reference to the physical location where the product will be sent    
	quantity smallint NOT NULL,
	request_complete boolean NOT NULL   DEFAULT FALSE	-- Indicates if the stock request at the physical location has been completed
)
;

CREATE TABLE purchase
(
	pk_id serial NOT NULL,	-- Identificador de la compra
	date timestamp without time zone NOT NULL,	-- Date when the purchase was made
	total_price integer NOT NULL   DEFAULT 0,	-- Total purchase value It's dynamically calculated
	email varchar(75) NOT NULL,	-- Email address of the person who made the purchase Must be a valid email address in the form: abc@dfg.hi
	name varchar(45) NOT NULL,	-- Full Name of the shopper
	doc_type varchar(2) NOT NULL,	-- Type of the identification of the shopper Allowed values:     - CC     - TI     - CE In capital letters
	identification varchar(15) NOT NULL,	-- Identification number of the person who made the purchase Must be a number and can't begin with 0
	telephone varchar(15) NOT NULL,	-- Telephone number of the person who made the purchase
	is_physical_purchase boolean NULL   DEFAULT NULL	-- Indicates whether the purchase was made at a physical location or, alternatively, was made online
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE category ADD CONSTRAINT "PK_category"
	PRIMARY KEY (pk_id)
;

ALTER TABLE department ADD CONSTRAINT "PK_department"
	PRIMARY KEY (pk_id)
;

ALTER TABLE ecommerce_purchase ADD CONSTRAINT "PK_ecommerce_purchase"
	PRIMARY KEY (pk_fk_purchase)
;

ALTER TABLE ecommerce_purchase ADD CONSTRAINT c_zip_code CHECK (zip_code ~* '^[1-9][0-9]*$')
;

CREATE INDEX "IXFK_ecommerce_purchase_department" ON ecommerce_purchase (fk_department ASC)
;

CREATE INDEX "IXFK_ecommerce_purchase_purchase" ON ecommerce_purchase (pk_fk_purchase ASC)
;

CREATE OR REPLACE FUNCTION trigger_is_ecommerce_purchase()
RETURNS TRIGGER AS $$
BEGIN
	--- duplicate inheritance
	IF EXISTS (SELECT 1 FROM physical_purchase WHERE physical_purchase.pk_fk_purchase = new.pk_fk_purchase) THEN
		RAISE EXCEPTION 'This purchase is already for a physical location';
	END IF;
	IF TG_OP = 'INSERT' THEN
        UPDATE purchase set is_physical_purchase = false WHERE purchase.pk_id = new.pk_fk_purchase;
		RETURN NEW;
	ELSE
		UPDATE purchase set is_physical_purchase = null WHERE purchase.pk_id = new.pk_fk_purchase;
		RETURN OLD;
    END IF;
	
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trigger_is_ecommerce_purchase BEFORE INSERT OR DELETE
    ON ecommerce_purchase
	FOR EACH ROW
    EXECUTE FUNCTION trigger_is_ecommerce_purchase ( )
;

ALTER TABLE employee ADD CONSTRAINT "PK_employee"
	PRIMARY KEY (pk_id)
;

ALTER TABLE employee ADD CONSTRAINT c_telephone CHECK (telephone ~* '^[1-9][0-9]*$')
;

ALTER TABLE employee ADD CONSTRAINT c_role_domain CHECK (employee.role in ('administrator', 'manager', 'cashier'))
;

ALTER TABLE employee ADD CONSTRAINT c_doc_type CHECK (doc_type IN ('CC', 'TI', 'CE'))
;

ALTER TABLE employee ADD CONSTRAINT c_identification CHECK (identification ~* '^[1-9][0-9]*$')
;

ALTER TABLE employee ADD CONSTRAINT c_fk_physical_location CHECK (role = 'administrator' OR fk_physical_location IS NOT NULL)
;

CREATE INDEX "IXFK_employee_physical_location" ON employee (fk_physical_location ASC)
;

ALTER TABLE inventory ADD CONSTRAINT "PK_inventary"
	PRIMARY KEY (pk_fk_product,pk_fk_physical_location)
;

ALTER TABLE inventory ADD CONSTRAINT c_display_quantity CHECK (quantity >= display_quantity)
;

ALTER TABLE inventory ADD CONSTRAINT c_quantity CHECK (quantity >= 0)
;

ALTER TABLE inventory ADD CONSTRAINT c_display_quantity_domain CHECK (display_quantity >= 0)
;

CREATE INDEX "IXFK_inventary_physical_location" ON inventory (pk_fk_physical_location ASC)
;

CREATE INDEX "IXFK_inventary_product" ON inventory (pk_fk_product ASC)
;

CREATE OR REPLACE FUNCTION trigger_available_ecommerce()
RETURNS TRIGGER AS $$
BEGIN
	IF TG_OP = 'INSERT' THEN
		NEW.ecommerce_available_quantity := NEW.quantity - NEW.display_quantity;
	ELSIF TG_OP = 'UPDATE' THEN
		IF NEW.quantity - OLD.quantity = 0 AND NEW.display_quantity - OLD.display_quantity = 0 THEN
			RETURN NEW;
		END IF;
		NEW.ecommerce_available_quantity 
			:= OLD.ecommerce_available_quantity + (NEW.quantity - OLD.quantity ) - (NEW.display_quantity - OLD.display_quantity);
	END IF;
	
	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trigger_available_ecommerce BEFORE INSERT OR UPDATE
    ON inventory
	FOR EACH ROW
    EXECUTE FUNCTION trigger_available_ecommerce ( )
;

ALTER TABLE physical_location ADD CONSTRAINT "PK_physical_location"
	PRIMARY KEY (pk_id)
;

ALTER TABLE physical_location ADD CONSTRAINT c_telephone CHECK (telephone ~* '^[1-9][0-9]*$')
;

ALTER TABLE physical_purchase ADD CONSTRAINT "PK_physic_purchase"
	PRIMARY KEY (pk_fk_purchase)
;

CREATE INDEX "IXFK_physic_purchase_employee" ON physical_purchase (fk_employee ASC)
;

CREATE INDEX "IXFK_physic_purchase_purchase" ON physical_purchase (pk_fk_purchase ASC)
;

CREATE OR REPLACE FUNCTION trigger_is_physical_purchase()
RETURNS TRIGGER AS $$
BEGIN
	--- duplicate inheritance
	IF EXISTS (SELECT 1 FROM ecommerce_purchase WHERE ecommerce_purchase.pk_fk_purchase = new.pk_fk_purchase) THEN
		RAISE EXCEPTION 'This purchase is already for the ecommerce';
	END IF;
	IF TG_OP = 'INSERT' THEN
        UPDATE purchase set is_physical_purchase = true WHERE purchase.pk_id = new.pk_fk_purchase;
		RETURN NEW;
	ELSE
		UPDATE purchase set is_physical_purchase = null WHERE purchase.pk_id = new.pk_fk_purchase;
		RETURN OLD;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trigger_is_physical_purchase BEFORE INSERT OR DELETE
    ON physical_purchase
	FOR EACH ROW
    EXECUTE FUNCTION trigger_is_physical_purchase ( )
;

CREATE OR REPLACE FUNCTION trigger_employee_is_cashier()
RETURNS TRIGGER AS $$
BEGIN
	IF (SELECT employee.role FROM employee WHERE employee.pk_id = NEW.fk_employee) != 'cashier' THEN
		RAISE EXCEPTION 'The employee must be a cashier';
	END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trigger_employee_is_cashier AFTER INSERT OR UPDATE
    ON physical_purchase
	FOR EACH ROW
    EXECUTE FUNCTION trigger_employee_is_cashier ( )
;

ALTER TABLE product ADD CONSTRAINT "PK_product"
	PRIMARY KEY (pk_id)
;

ALTER TABLE product ADD CONSTRAINT c_price CHECK (price >= 0)
;

CREATE INDEX "IXFK_product_category" ON product (fk_category ASC)
;

ALTER TABLE product_in_purchase ADD CONSTRAINT "PK_product_in_purchase"
	PRIMARY KEY (pk_fk_product,pk_fk_purchase)
;

CREATE INDEX "IXFK_product_in_purchase_product" ON product_in_purchase (pk_fk_product ASC)
;

CREATE INDEX "IXFK_product_in_purchase_purchase" ON product_in_purchase (pk_fk_purchase ASC)
;

CREATE OR REPLACE FUNCTION trigger_update_total_price()
RETURNS TRIGGER AS $$
BEGIN
	IF TG_OP = 'DELETE' OR TG_OP = 'UPDATE' THEN
		UPDATE purchase set total_price = purchase.total_price - OLD.unit_price*OLD.quantity WHERE purchase.pk_id = OLD.pk_fk_purchase;
	END IF;
	IF TG_OP = 'INSERT' OR TG_OP = 'UPDATE' THEN
		UPDATE purchase set total_price = purchase.total_price + NEW.unit_price*NEW.quantity WHERE purchase.pk_id = NEW.pk_fk_purchase;
    END IF;
	
	IF TG_OP = 'DELETE' THEN
		RETURN OLD;
	ELSE
		RETURN NEW;
	END IF;
	
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trigger_update_total_price AFTER INSERT OR DELETE or UPDATE
    ON product_in_purchase
	FOR EACH ROW
    EXECUTE FUNCTION trigger_update_total_price ( )
;

ALTER TABLE product_request ADD CONSTRAINT "PK_product_request"
	PRIMARY KEY (pk_fk_product,pk_fk_purchase,pk_fk_physical_location)
;

CREATE INDEX "IXFK_product_request_physical_location" ON product_request (pk_fk_physical_location ASC)
;

CREATE INDEX "IXFK_product_request_product_in_purchase" ON product_request (pk_fk_product ASC,pk_fk_purchase ASC)
;


;

ALTER TABLE purchase ADD CONSTRAINT "PK_purchase"
	PRIMARY KEY (pk_id)
;

ALTER TABLE purchase ADD CONSTRAINT c_email CHECK (email ~* '^[A-Za-z0-9._+%-]+@[A-Za-z0-9.-]+[.][A-Za-z]+$')
;

ALTER TABLE purchase ADD CONSTRAINT c_doc_type CHECK (doc_type IN ('CC', 'TI', 'CE'))
;

ALTER TABLE purchase ADD CONSTRAINT c_identification CHECK (identification ~* '^[1-9][0-9]*$')
;

ALTER TABLE purchase ADD CONSTRAINT c_telephone CHECK (telephone ~* '^[1-9][0-9]*$')
;

/* Create Foreign Key Constraints */

ALTER TABLE ecommerce_purchase ADD CONSTRAINT "FK_ecommerce_purchase_department"
	FOREIGN KEY (fk_department) REFERENCES department (pk_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE ecommerce_purchase ADD CONSTRAINT "FK_ecommerce_purchase_purchase"
	FOREIGN KEY (pk_fk_purchase) REFERENCES purchase (pk_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE employee ADD CONSTRAINT "FK_employee_physical_location"
	FOREIGN KEY (fk_physical_location) REFERENCES physical_location (pk_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE inventory ADD CONSTRAINT "FK_inventary_physical_location"
	FOREIGN KEY (pk_fk_physical_location) REFERENCES physical_location (pk_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE inventory ADD CONSTRAINT "FK_inventary_product"
	FOREIGN KEY (pk_fk_product) REFERENCES product (pk_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE physical_purchase ADD CONSTRAINT "FK_physic_purchase_employee"
	FOREIGN KEY (fk_employee) REFERENCES employee (pk_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE physical_purchase ADD CONSTRAINT "FK_physic_purchase_purchase"
	FOREIGN KEY (pk_fk_purchase) REFERENCES purchase (pk_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE product ADD CONSTRAINT "FK_product_category"
	FOREIGN KEY (fk_category) REFERENCES category (pk_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE product_in_purchase ADD CONSTRAINT "FK_product_in_purchase_product"
	FOREIGN KEY (pk_fk_product) REFERENCES product (pk_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE product_in_purchase ADD CONSTRAINT "FK_product_in_purchase_purchase"
	FOREIGN KEY (pk_fk_purchase) REFERENCES purchase (pk_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE product_request ADD CONSTRAINT "FK_product_request_physical_location"
	FOREIGN KEY (pk_fk_physical_location) REFERENCES physical_location (pk_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE product_request ADD CONSTRAINT "FK_product_request_product_in_purchase"
	FOREIGN KEY (pk_fk_product,pk_fk_purchase) REFERENCES product_in_purchase (pk_fk_product,pk_fk_purchase) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON COLUMN category.pk_id
	IS 'Category identifier'
;

COMMENT ON COLUMN category.name
	IS 'Category name'
;

COMMENT ON COLUMN category.description
	IS 'Short description of the type of product included in the category'
;

 

COMMENT ON COLUMN department.pk_id
	IS 'Department identifier'
;

COMMENT ON COLUMN department.name
	IS 'Department name'
;

 

COMMENT ON COLUMN ecommerce_purchase.pk_fk_purchase
	IS 'Identifier of the base purchase'
;

COMMENT ON COLUMN ecommerce_purchase.fk_department
	IS 'Department where the delivery address is located'
;

COMMENT ON COLUMN ecommerce_purchase.delivery_address
	IS 'Delivery address for online purchases.
It only has a value if the purchase was online'
;

COMMENT ON COLUMN ecommerce_purchase.zip_code
	IS 'Zip code corresponding to the delivery address
It must be a number and can''t begin with 0
It only has a value if the purchase was online'
;

COMMENT ON COLUMN employee.pk_id
	IS 'Employee identifier'
;

COMMENT ON COLUMN employee.fk_physical_location
	IS 'Identify the physical point that the employee belongs to.
This field can be NULL if its role is administrator'
;

COMMENT ON COLUMN employee.name
	IS 'Employee name'
;

COMMENT ON COLUMN employee.last_name
	IS 'Employee last name'
;

COMMENT ON COLUMN employee.telephone
	IS 'Employee telephone
It must be a number and can''t begin with 0'
;

COMMENT ON COLUMN employee.role
	IS 'Employee role in the company, depending on its value, the employee will have a specific set of permissions. Only the following values should be allowed:

    - Administrator
    - Manager
    - Cashier'
;

COMMENT ON COLUMN employee.password
	IS 'Employee password for get access'
;

COMMENT ON COLUMN employee.identification
	IS 'Identification number of the employee
Must be a number and can''t begin with 0'
;

 

COMMENT ON COLUMN inventory.pk_fk_product
	IS 'Identifier of the product stored in the inventory associated with a physical location'
;

COMMENT ON COLUMN inventory.pk_fk_physical_location
	IS 'Identifier of the physical location that own of the inventory'
;

COMMENT ON COLUMN inventory.quantity
	IS 'Amount of the product stored at the physical location'
;

COMMENT ON COLUMN physical_location.pk_id
	IS 'Physical location identifier'
;

COMMENT ON COLUMN physical_location.direction
	IS 'Physical location address'
;

COMMENT ON COLUMN physical_location.telephone
	IS 'The telephone number of the physical location.
It must be a number and can''t begin with 0'
;

 

COMMENT ON COLUMN physical_purchase.pk_fk_purchase
	IS 'Identifier of the base purchase'
;

COMMENT ON COLUMN product.pk_id
	IS 'Identifier of product'
;

COMMENT ON COLUMN product.fk_id_base_product
	IS 'Given that the products can have variants.
This field has the identifier of base product.'
;

COMMENT ON COLUMN product.name
	IS 'Name of product'
;

COMMENT ON COLUMN product.description
	IS 'Short description of the product'
;

COMMENT ON COLUMN product.price
	IS 'Sell price of product'
;

COMMENT ON COLUMN product.image
	IS 'File name that contains the image of the product'
;

COMMENT ON COLUMN product.active
	IS 'It indicates if the product should be visible in the store.'
;

COMMENT ON COLUMN product.fk_category
	IS 'References the category that the product belongs to'
;

COMMENT ON CONSTRAINT c_price ON product IS 'The price field must be positive'
;

 

COMMENT ON COLUMN product_in_purchase.pk_fk_product
	IS 'Reference to product in the purchase'
;

COMMENT ON COLUMN product_in_purchase.pk_fk_purchase
	IS 'Reference to the purchase to which the product belongs'
;

COMMENT ON COLUMN product_in_purchase.quantity
	IS 'Quantity of the product that belongs to the purchase'
;

COMMENT ON COLUMN product_in_purchase.unit_price
	IS 'Price per unit of the product at the time the purchase was completed'
;

COMMENT ON COLUMN product_request.pk_fk_physical_location
	IS 'Reference to the physical location where the product will be sent    '
;

COMMENT ON COLUMN product_request.request_complete
	IS 'Indicates if the stock request at the physical location has been completed'
;

COMMENT ON COLUMN purchase.pk_id
	IS 'Identificador de la compra'
;

COMMENT ON COLUMN purchase.date
	IS 'Date when the purchase was made'
;

COMMENT ON COLUMN purchase.total_price
	IS 'Total purchase value
It''s dynamically calculated'
;

COMMENT ON COLUMN purchase.email
	IS 'Email address of the person who made the purchase
Must be a valid email address in the form: abc@dfg.hi'
;

COMMENT ON COLUMN purchase.name
	IS 'Full Name of the shopper'
;

COMMENT ON COLUMN purchase.doc_type
	IS 'Type of the identification of the shopper
Allowed values:
    - CC
    - TI
    - CE
In capital letters'
;

COMMENT ON COLUMN purchase.identification
	IS 'Identification number of the person who made the purchase
Must be a number and can''t begin with 0'
;

COMMENT ON COLUMN purchase.telephone
	IS 'Telephone number of the person who made the purchase'
;

COMMENT ON COLUMN purchase.is_physical_purchase
	IS 'Indicates whether the purchase was made at a physical location or, alternatively, was made online'
;

 
