
### Ejemplo loguin 1
POST http://localhost:3200/api/auth/singin
Content-Type: application/json

# body
{
    "userId": 1,
    "password": "AdminB)343" 
}
### Ejemplo loguin 2
POST http://localhost:3200/api/auth/singin
Content-Type: application/json

# body
{
    "userId": 6,
    "password": "0 James Soliban" 
}

### Ejemplo registro
POST http://localhost:3200/api/auth/singup
Content-Type: application/json
Authorization: barer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzMxMzE1NTE5LCJleHAiOjE3MzEzMjI3MTl9.N_ByzZhrwqMcH9-fpCTsu5VGywvsZyl2Aq5d6vWWYm8

{
    "name": "James",
    "lastName": "Soliban",
    "telephone": "111011",
    "role": "administrator"
}
