
### Ejemplo loguin 1
POST http://localhost:3200/api/auth/singin
Content-Type: application/json

# body
{
    "userId": 1,
    "password": "AdminB)343" 
}
### Ejemplo loguin 2
POST http://localhost:3200/api/auth/singin
Content-Type: application/json

{
    "userId": 2,
    "password": "asdsd" 
}

###
@token = token

### Ejemplo registro
POST http://localhost:3200/api/auth/singup
Content-Type: application/json
Authorization: barer {{token}}

{
    "name": "Marcelo",
    "locationId": 1,
    "lastName": "Conocelo",
    "email": "marcelo@gg.com",
    "telephone": "111011",
    "role": "cashier",
    "docType": "CC",
    "docNumber": "1001"
}

### Ejemplo peticion del role del usuario
GET http://localhost:3200/api/auth/get-role
Content-Type: application/json
Authorization: barer {{token}}