### Consultar todos los inventarios
http://localhost:3200/api/inventory/
Authorization: barer {{token}}

### Consultar el inventario 1
GET http://localhost:3200/api/inventory/?locationId=1
Content-Type: application/json
Authorization: barer {{token}}

###
@token = token
###

### Actualizar inventario
PUT http://localhost:3200/api/inventory
Content-Type: application/json
Authorization: barer {{token}}

{
    "productId": 1,
    "physicalLocationId": 1,
    "quantity": 39,
    "displayQuantity": 3
}