###Consultar todos los inventarios
http://localhost:3200/api/inventory/list
Authorization: barer {{token}}

###Consultar el inventario 
http://localhost:3200/api/inventory/list?id=1

##Consultar el inventario 1
GET http://localhost:3200/api/inventory/list?id=1
Content-Type: application/json
Authorization: barer {{token}}

###
@token = token
###

### Actualizar inventario
PUT http://localhost:3200/api/inventory
Content-Type: application/json
Authorization: barer {{token}}

{
    "productId": 4,
    "physicalLocationId": 2,
    "quantity": 39,
    "displayQuantity": 38
}