

### Ejemplo base
POST http://localhost:3200/api/purchase/initialize-purchase
Content-Type: application/json

{
    "basicUserData": {
        "email": "elpepe@gmail.com",
        "name": "Pedro Sanchez",
        "docType": "CC",
        "identification": "0005",
        "telephone": "0312"
    },
    "addressData": {
        "departmentId": 1,
        "deliveryAddress": "Carrera del pepe",
        "zipCode": "0102"
    }, 
    "productList": [
        {
            "id": 1,
            "quantity": 3
        },
        {
            "id": 2,
            "quantity": 3
        }
    ]
}

### Prueba asignacion de stock con puntos fisicos variados
POST http://localhost:3200/api/purchase/initialize-purchase
Content-Type: application/json

{
    "basicUserData": {
        "email": "elpepe@gmail.com",
        "name": "Pedro Sanchez",
        "docType": "CC",
        "identification": "10005",
        "telephone": "312"
    },
    "addressData": {
        "departmentId": 1,
        "deliveryAddress": "Carrera del pepe",
        "zipCode": "12399"
    }, 
    "productList": [
        {
            "id": 1,
            "quantity": 37
        },
        {
            "id": 2,
            "quantity": 3
        },
        {
            "id": 3,
            "quantity": "3"
        }
    ]
}

### No deberia aceptarla porque no hay stock
POST http://localhost:3200/api/purchase/initialize-purchase
Content-Type: application/json

{
    "basicUserData": {
        "email": "elpepe@gmail.com",
        "name": "Pedro Sanchez",
        "docType": "CC",
        "identification": "10005",
        "telephone": "312"
    },
    "addressData": {
        "departmentId": 1,
        "deliveryAddress": "Carrera del pepe",
        "zipCode": "12399"
    }, 
    "productList": [
        {
            "id": 1,
            "quantity": 2
        },
        {
            "id": 2,
            "quantity": 300
        },
        {
            "id": 3,
            "quantity": 3
        }
    ]
}

### Completar compra
POST http://localhost:3200/api/purchase/complete-purchase
Content-Type: application/json

{
    "purchaseId": 1
}

### Eliminar una compra

POST http://localhost:3200/api/purchase/reject-purchase
Content-Type: application/json

{
    "purchaseId": 2
}

###
# token del cajero
@token = token

### Compra en POS
POST http://localhost:3200/api/purchase/pos-purchase
Content-Type: application/json
Authorization: Barer {{token}}

{
    "basicUserData": {
        "email": "a@a.com",
        "name": "james",
        "docType": "CC",
        "identification": "123456789012345",
        "telephone": "11"
    },
    "productList": [
        {
            "id": 1,
            "quantity": 3
        },
        {
            "id": 2,
            "quantity": 3
        }
    ],
    "locationId": 1
}